packages:
  - apps/*
  - packages/*
  - proxy-server
  - tiling-services/*
onlyBuiltDependencies:
  - '@bundled-es-modules/glob'
  - '@vaadin/vaadin-usage-statistics'
  - chromedriver
  - esbuild
  - sharp
  - style-dictionary
  - unrs-resolver
