name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  proxy-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: proxy-server/package-lock.json
      - name: Install
        working-directory: proxy-server
        run: npm ci
      - name: Test
        working-directory: proxy-server
        env:
          NWS_USER_AGENT: '(Vortexa, contact@example.com)'
          RAINVIEWER_ENABLED: 'true'
        run: npm test --silent

  dashboard-app-unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: dashboard-app/package-lock.json
      - name: Install
        working-directory: dashboard-app
        run: npm ci
      - name: Unit tests
        working-directory: dashboard-app
        run: npm test --silent

  dashboard-app-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: dashboard-app/package-lock.json
      - name: Install deps
        working-directory: dashboard-app
        run: npm ci
      - name: Install Playwright Browsers
        working-directory: dashboard-app
        run: npx playwright install --with-deps
      - name: E2E tests
        working-directory: dashboard-app
        run: npm run e2e

  glm-toe-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        working-directory: tiling-services/glm_toe
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          pip install pytest
      - name: Run tests
        working-directory: tiling-services/glm_toe
        run: |
          source .venv/bin/activate
          pytest -q
